### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by cvazhe** [naver-ai/dual-teacher#3]
作者您好，我看您给的代码中是ADE20K的训练，请问我要训练VOC2012和cityscape数据集的话我要修改哪里呀，我自己没有找到。然后数据集还用像ADE20K数据集那样进行划分么？请作者给出提示，谢谢。

**Comment by NaJaeMin92** [comment]
@cvazhe Sorry for the late reply.

Since we used SegFormer with MiT-B1 for ADE20K, you should replace the network with DeepLabv3+ based on ResNet-50/-101 backbones. Also, you need to add corresponding dataloaders for PASCAL VOC and Cityscapes datasets.

Please note that we didn't make custom splits for PASCAL VOC and Cityscapes; we used public partitions availabe in other reops like U2PL.
